---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: trustification
spec:
  displayName: trustification
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: trustification-guac
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "private"}'
spec:
  application: trustification
  componentName: trustification-guac
  source:                                                                                                                                                                                     
    git:                                                                                                                                                                                      
      context: ./                                                                                                                                                                             
      devfileUrl: https://raw.githubusercontent.com/devfile-samples/devfile-sample-go-basic/main/devfile.yaml                                                                                 
      dockerfileUrl: dockerfiles/Dockerfile.guac-ubi                                                                                                                                          
      revision: trustification-main                                                                                                                                                           
      url: https://github.com/trustification/guac
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: trustification-service
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "private"}'
spec:
  application: trustification
  componentName: trustification-product-1-0-z
  source:                                                                                                                                                                                     
    git:                                                                                                                                                                                      
      devfileUrl: https://raw.githubusercontent.com/nodeshift-starters/devfile-sample/main/devfile.yaml
      dockerfileUrl: https://raw.githubusercontent.com/trustification/trustification/stable/container_files/Containerfile.services
      revision: release/1.0.z
      url: https://github.com/trustification/trustification
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: trustification-tests
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "private"}'
spec:
  application: trustification
  componentName: trustification-product-test-1-0-z
  source:                                                                                                                                                                                     
    git:                                                                                                                                                                                      
      context: ./                                                                                                                                                                             
      devfileUrl: https://raw.githubusercontent.com/devfile-samples/devfile-sample-go-basic/main/devfile.yaml                                                                                 
      dockerfileUrl: https://raw.githubusercontent.com/trustification/trustification/release/1.0.z/container_files/Containerfile.tests
      revision: release/1.0.z
      url: https://github.com/trustification/trustification
